eliminar lógica de creación de despliegue y comentarios relacionados en action.yml

diff --git a/github-deployment/action.yml b/github-deployment/action.yml
--- a/github-deployment/action.yml
+++ b/github-deployment/action.yml
@@ -13,11 +13,6 @@ inputs:
     required: false
     type: string
     default: 2026-03-10
-  # create:
-  #   description: Whether to create the deployment
-  #   required: false
-  #   type: boolean
-  #   default: false
   deployment-id:
     description: ID of the deployment to update status for (if not creating a new deployment)
     required: false
@@ -77,13 +72,6 @@ runs:
            exit 0
         fi
 
-        # # export deployment_id = '' if input.create !== true or input.create !== 'true'
-        # if [ "${{ inputs.create }}" != "true" ] && [ "${{ inputs.create }}" != "True" ]; then
-        #   echo "Input 'create' is not true, skipping deployment creation..."
-        #   echo "deployment_id=" >> $GITHUB_OUTPUT
-        #   exit 0
-        # fi
-
         RESPONSE=$(curl -s -X POST \
           -H "Authorization: token ${{ inputs.github-token }}" \
           -H "Accept: application/vnd.github+json" \
@@ -99,6 +87,13 @@ runs:
         
         DEPLOYMENT_ID=$(echo $RESPONSE | jq -r '.id')
         echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
+
+        if [ -z "$DEPLOYMENT_ID" ] || [ "$DEPLOYMENT_ID" = "null" ]; then
+          echo "Failed to create deployment. Response: $RESPONSE" >&2
+          exit 1
+        else 
+          echo "Deployment created with ID: $DEPLOYMENT_ID"
+        fi
     - name: Update Deployment Status
       id: update
       if: steps.deployment.outputs.deployment_id != '' && (inputs.success == true || inputs.success == 'true' || inputs.state != '')
